### ISSUE TITLE
Throws an error for scheduler = "processes"

### ISSUE THREAD

**Issue by adityaponnada** [qutang/location_matters#1]
it threw an error when i tried:
`pipenv run python prepare_class_set.py ./muss_data/ scheduler="processes"`

It seems to be working fine without the scheduler. Perhaps you want to include this information in the read.me.

**Comment by adityaponnada** [comment]
![image](https://user-images.githubusercontent.com/16159941/56437683-5fa52200-62ae-11e9-8417-5cb595fb318b.png)

That was the error

**Comment by qutang** [comment]
Syntax should be "--scheduler=processes".
