### ISSUE TITLE
output folder created without the current date

### ISSUE THREAD

**Issue by adityaponnada** [qutang/location_matters#2]
For me it created an output folder without the current date: DerivedCrossParticipants/product_run.

This folder is empty.

Also, the run has an error message:

![image](https://user-images.githubusercontent.com/16159941/56437868-fe318300-62ae-11e9-95c0-be043eee53e6.png)

**Comment by qutang** [comment]
You have to install graphviz on windows.

Qu
2019年4月19日 -0400 PM2:25 Aditya Ponnada <notifications@github.com>，写道：

**Comment by adityaponnada** [comment]
But that is only for the workflow pdf right?

**Comment by qutang** [comment]
Yes, maybe I should skip that error.

Qu
2019年4月19日 -0400 PM2:28 Aditya Ponnada <notifications@github.com>，写道：

**Comment by adityaponnada** [comment]
the output folder is empty nevertheless. it is also created without the [CURRENT_DATE]

**Comment by qutang** [comment]
The [CURRENT_DATE] description is out of date. I have removed that.

**Comment by adityaponnada** [comment]
great! When I run the script without the scheduler, the output folder is empty

**Comment by qutang** [comment]
I'll check that. What was the error message when you use the scheduler

**Comment by adityaponnada** [comment]
This is the error:

![image](https://user-images.githubusercontent.com/16159941/56444066-317f0c80-62c5-11e9-881a-f3d4eaff7053.png)

**Comment by adityaponnada** [comment]
BTW, I get the same error when trying with the sampling-rate=80 to compute features:

![image](https://user-images.githubusercontent.com/16159941/56444158-976b9400-62c5-11e9-8825-21210fd23294.png)

**Comment by qutang** [comment]
It seems the syntax of your input argument has some problem

**Comment by qutang** [comment]
You need the --scheduler='processes'

**Comment by qutang** [comment]
And without quote. I'll update the README

**Comment by adityaponnada** [comment]
`(base) C:\Users\Dharam\MUSS>pipenv run python prepare_class_set.py ./muss_data/muss-data/ sampling-rate=80`
```
prepare_class_set.py: Received extra arguments: sampling-rate=80
Usage: prepare_class_set.py [OPTIONS] input-folder
```

**Comment by qutang** [comment]
The same. Options should have `--` before it.

**Comment by adityaponnada** [comment]
the folder name duplicates because I ended up copying the compressed file. So it created a subfolder but that is not the problem.

**Comment by qutang** [comment]
there shouldn't be an extra `muss_data` in `muss_data`. It should be the folder structure of a mhealth dataset.

**Comment by adityaponnada** [comment]
I copied the muss_data compressed folder. So the decompressed one had the muss_data as the sub folder. That is why I added ./muss_data/muss_data/

**Comment by qutang** [comment]
No, don't do that. Move that one level up.
