### ISSUE TITLE
Running the model on any raw data

### ISSUE THREAD

**Issue by adityaponnada** [qutang/location_matters#3]
is it possible to run this model on any raw data? for instance, if I only have to run this model on an hour file I have, can I do something like:

`python computeFeatures.py <input raw file> -o <output feature file>`
`python testModel.py <input feature file> -o <output prediction file>`

This is precisely what I need.

**Comment by qutang** [comment]
You may use the prepare_feature_set.py to run on new data. However, you have to make sure the new data are stored in mhealth folder structure, and each file is named according to the mhealth format. And you have to provide an extra location_mapping.csv file (see that in muss_data) to map sensor id to placement.

**Comment by adityaponnada** [comment]
Got it! I can perhaps do it now!
